baseURL = "https://hnevarez.com"
languageCode = "en-us"
title = "Hector Nevarez"
theme = "showfolio"

[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "Hector Nevarez"
  authorEmail = "eglen.neva@gmail.com"
  authorImage = "headshot.jpg"
  DarkMode = true

  postSummariesFrontPage = 6
  mainSections = ["blog"]

  copyright = "Copyright © 2022 - Hector Nevarez · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hector Nevarez"
  tagline = "Software Engineer @"
  company = "ModalAI"
  description = "Embedded robotics software engineer with a passion for A.I. and robotics"
  contact = "mailto:eglen.neva@gmail.com"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/hector-nevarez-799997174/"
  github = "https://github.com/HectorENevarez"

[params.blogs]
  blogPosts = [
              "/beginners-guide-to-neural-networks/" ,
              "fsdf"
              ]

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Whoami"
  url = "/whoami/"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3